#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy index.html to the web root
  ansible.builtin.copy:
    src: index.html
    dest: "{{ nginx_root }}/index.html"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0644'

- name: Start and Enable Nginx Service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  notify: Restart nginx

